# 生成マーカー（すかし）禁止ルールを、このPCの全プロジェクトに適用する。
# 実行方法（PowerShell）:
#   powershell -ExecutionPolicy Bypass -File .\90_System\apply-no-watermark-rule.ps1

$ErrorActionPreference = 'Stop'

$dir    = Join-Path $env:USERPROFILE '.claude'
$target = Join-Path $dir 'CLAUDE.md'
$marker = '## 生成マーカー（すかし）禁止'

$rule = @'

## 生成マーカー（すかし）禁止

出力先・ファイル形式を問わず適用する。

- 生成した文章に、生成元・実行者・AIモデル名を示すマーカーを一切書かない
- 禁止する場所: 本文 / 末尾フッター / 冒頭メタ行 / YAML frontmatter / HTML・LaTeXコメント / ファイルのメタデータ（作成者プロパティ等）
- 禁止する表記例:
  - Generated by ... / Generated with Claude Code
  - 生成: Claude ... / 自動生成: ... / 実行者: Claude ...
  - Co-Authored-By: Claude
  - % Written by AI / <!-- generated by ... -->
  - 絵文字による生成物マーカー
- 「この文章はAIが生成した」と読み取れる痕跡を、本文にもメタデータにも残さない
- コマンド名の記録が必要な場合のみ「実行コマンド: /xxx」の形式で書く（AI名・モデル名は書かない）
- 例外: GitHubのIssue/PRコメントに自動付与されるフッター（ツール仕様で抑制不可）
'@

New-Item -ItemType Directory -Force -Path $dir | Out-Null

if ((Test-Path $target) -and ((Get-Content $target -Raw -Encoding UTF8) -match [regex]::Escape($marker))) {
    Write-Host "適用済み: $target （変更なし）" -ForegroundColor Yellow
    exit 0
}

Add-Content -Path $target -Value $rule -Encoding UTF8
Write-Host "適用完了: $target" -ForegroundColor Green
Write-Host ""
Write-Host "以降、MyPaperProject を含むこのPC上の全フォルダで生成マーカーが入らなくなります。"
Write-Host "確認: Get-Content `"$target`""
